import { TwipHeroSection } from '../components/patterns/hero-section.js';
import { TwipFeaturesSection } from '../components/patterns/features-section.js';
import { TwipCtaSection } from '../components/patterns/cta-section.js';
import { TwipFaqSection } from '../components/patterns/faq-section.js';
import { TwipTestimonialsSection } from '../components/patterns/testimonials-section.js';
import { TwipStatsSection } from '../components/patterns/stats-section.js';
import { TwipLogoCloudSection } from '../components/patterns/logo-cloud-section.js';
import { TwipNewsletterSection } from '../components/patterns/newsletter-section.js';
import { TwipPricingSection } from '../components/patterns/pricing-section.js';
import { TwipTeamSection } from '../components/patterns/team-section.js';
import { TwipStepsSection } from '../components/patterns/steps-section.js';
import { TwipBentoSection } from '../components/patterns/bento-section.js';
import { TwipBannerSection } from '../components/patterns/banner-section.js';
import { TwipSplitSection } from '../components/patterns/split-section.js';
import { TwipContactSection } from '../components/patterns/contact-section.js';
import { TwipContentSection } from '../components/patterns/content-section.js';
import { TwipSocialProofSection } from '../components/patterns/social-proof-section.js';
import { defineElement } from '../internal/define.js';

defineElement('twip-hero-section', TwipHeroSection);
defineElement('twip-features-section', TwipFeaturesSection);
defineElement('twip-cta-section', TwipCtaSection);
defineElement('twip-faq-section', TwipFaqSection);
defineElement('twip-testimonials-section', TwipTestimonialsSection);
defineElement('twip-stats-section', TwipStatsSection);
defineElement('twip-logo-cloud-section', TwipLogoCloudSection);
defineElement('twip-newsletter-section', TwipNewsletterSection);
defineElement('twip-pricing-section', TwipPricingSection);
defineElement('twip-team-section', TwipTeamSection);
defineElement('twip-steps-section', TwipStepsSection);
defineElement('twip-bento-section', TwipBentoSection);
defineElement('twip-banner-section', TwipBannerSection);
defineElement('twip-split-section', TwipSplitSection);
defineElement('twip-contact-section', TwipContactSection);
defineElement('twip-content-section', TwipContentSection);
defineElement('twip-social-proof-section', TwipSocialProofSection);
